"""empty message

Revision ID: 149d598cf92b
Revises: 
Create Date: 2021-02-05 10:33:50.087696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149d598cf92b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('classId', sa.Integer(), nullable=False),
    sa.Column('className', sa.String(length=20), nullable=True),
    sa.Column('subject', sa.String(length=20), nullable=True),
    sa.Column('tutorId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tutorId'], ['tutor.tutorId'], ),
    sa.PrimaryKeyConstraint('classId')
    )
    op.create_table('tutor',
    sa.Column('tutorId', sa.Integer(), nullable=False),
    sa.Column('pw', sa.String(length=20), nullable=False),
    sa.Column('classId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classId'], ['classes.classId'], ),
    sa.PrimaryKeyConstraint('tutorId')
    )
    op.create_table('student',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('pw', sa.String(length=20), nullable=False),
    sa.Column('classId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['classId'], ['classes.classId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('userId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('tutor')
    op.drop_table('classes')
    # ### end Alembic commands ###
